auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            lipbin.com
url:              http://lipbin.com
feed:             /atom.xml
author:
    name:         lipbin
description:      "lipbin\'s Blog"

